service: decent-visualizer-airtable

frameworkVersion: "2"
useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    region: us-west-2
    memorySize: 256

plugins:
    - serverless-offline-ssm
    - serverless-offline
    - serverless-plugin-typescript

functions:
    # Synchronizes shot data from visualizer.coffee -> Airtable
    coffeeSync:
        handler: handler.coffeeSync
        events:
            - http:
                  path: decent/webhook
                  method: post
            - schedule: rate(30 minutes)
        environment:
            VISUALIZER_BASE_URL: https://visualizer.coffee
            VISUALIZER_USER: ${ssm:/visualizer-airtable/visualizer/user~true}
            VISUALIZER_PASSWORD: ${ssm:/visualizer-airtable/visualizer/password~true}
            AIRTABLE_API_KEY: ${ssm:/visualizer-airtable/airtable/api-key~true}
            AIRTABLE_BASE: ${ssm:/visualizer-airtable/airtable/base~true}
            FIELD_COFFEE_MACHINE: ${ssm:/visualizer-airtable/coffee-machine}
            FIELD_GRINDER: ${ssm:/visualizer-airtable/grinder}
            HMAC_SECRET: ${ssm:/visualizer-airtable/hmac-secret~true}

custom:
    serverless-offline-ssm:
        stages:
            - offline
