service: decent-visualizer-airtable

frameworkVersion: "2"
useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    region: us-west-2

plugins:
    - serverless-offline-ssm
    - serverless-offline
    - serverless-plugin-typescript

functions:
    # Synchronizes shot data from visualizer.coffee -> Airtable
    coffeeSync:
        handler: handler.coffeeSync
        events:
            - schedule: rate(10 minutes)
        environment:
            VISUALIZER_BASE_URL: https://visualizer.coffee
            VISUALIZER_USER: ${ssm:/visualizer-airtable/visualizer/user~true}
            VISUALIZER_PASSWORD: ${ssm:/visualizer-airtable/visualizer/password~true}
            AIRTABLE_API_KEY: ${ssm:/visualizer-airtable/airtable/api-key~true}
            AIRTABLE_BASE: ${ssm:/visualizer-airtable/airtable/base~true}

custom:
    serverless-offline-ssm:
        stages:
            - offline
