service: decent-visualizer-airtable

frameworkVersion: "2"

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221

# stage: dev
region: us-west-2

functions:
    # Synchronizes shot data from visualizer.coffee -> Airtable
    coffeeSync:
        handler: handler.coffeeSync
        events:
            schedule: rate(10 minutes)
        environment:
            VISUALIZER_BASE_URL: https://visualizer.coffee
